### PR TITLE
Grid Framework

### PR DESCRIPTION
**Pull request by camfilho**
We used our framework to clone http://how-to-meditate.org/

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi team

Your grid framework was properly implemented. 

- [x] Ensure you pass the linter checks.

[**Optional**]
Your UI is not coming up properly - the arrangment, it does not look like the site you cloned [how to medidate](http://how-to-meditate.org/)

Please work on this and submit another code review.

#### ``` Have a great day``` :slightly_smiling_face: 

@ Uchechukwu Henry Inyama

**Comment by camfilho** [comment]
Hi, fixed all linter errors on the .css files

**Comment by suretrust** [comment]
Hi @lucaasdfg and @camfilho,

Great job guys :raised_hands:, however, linter tests still fail. 

linter

Ensure you pass all linter tests as shown in the image below.

linter2

Please submit for another code review after fixing the linter issues.

Happy coding guys! :man_technologist: :man_technologist:

**Comment by camfilho** [comment]
fixed now @suretrust

**Comment by suretrust** [comment]
Hi @camfilho and @lucaasdfg :raised_hands:

Great job! **Let's get this merged! :tada:** 

_Good luck with other projects and happy coding!_

**Pull request merged**
